apiVersion: v1
kind: Service
metadata: 
  name: database-service
  namespace: days-off
  labels:
    app: sql-tasks
spec:
  selector:
    app: sql-tasks
  type: NodePort
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
    nodePort: 31001