apiVersion: v1
kind: Service
metadata: 
  name: backend-service
  namespace: days-off
  labels:
    app: backend-app
spec:
  selector:
    app: backend-app
  type: NodePort
  ports:
  - protocol: TCP
    port: 31002
    targetPort: 31002
    nodePort: 31002