apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto-depl
  namespace: days-off
  labels:
    app: mosquitto-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto-broker
  template:
    metadata:
      labels:
        app: mosquitto-broker
    spec:
      hostNetwork: true
      restartPolicy: Always
      containers:
      - image: eclipse-mosquitto
        name: mosquitto-container
        ports:
        - containerPort: 1883
        volumeMounts:
        - mountPath: /mosquitto/conf/
          name: mosquitto-volume
      volumes:
      - name: mosquitto-volume
        configMap:
          name: mosquitto-config