apiVersion: v1
kind: Service
metadata:
  name: mosquitto-service
spec:
  type: NodePort
  selector:
    app: mosquitto-broker
  ports:
  - port: 1883
    targetPort: default
    protocol: TCP
    name: default
  - port: 8080
    targetPort: websocket
    protocol: TCP
    name: websocket