apiVersion: v1
kind: ConfigMap
metadata: 
  name: mosquitto-config
  namespace: days-off
  labels:
    app: mosquitto-broker
data:
  mosquitto.conf: |
    allow_anonymous true
    listener 1883
    persistence false
    persistence_location /var/lib/mosquitto/data
    log_dest file var/lib/mosquitto/log
