#https://dev.to/musolemasu/deploy-a-mysql-database-server-in-kubernetes-static-dpc
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stateful-db2
  namespace: days-off
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql-tasks2
  template:
    metadata:
      labels:
        app: sql-tasks2
    spec:
      containers:
      - name: deployment-db
        image: mysql
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_DATABASE
          value: company
        - name: MYSQL_ROOT_PASSWORD
          value: x#9kQL4X
        - name: MYSQL_USER
          value: manos
        - name: MYSQL_PASSWORD
          value: x#9kQL4X
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
        


      