apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      restartPolicy: Always
      containers:
      - name: backend
        image: manoshua/days-off-app:backend
        ports:
        - containerPort: 31002
      imagePullSecrets:
      - name: credentials


      