apiVersion: v1
kind: Service
metadata: 
  name: database-service
  labels:
    app: sql-tasks
spec:
  selector:
    app: sql-tasks
  clusterIP: 10.152.183.121
  ports:
  - protocol: TCP
    port: 3306
