apiVersion: v1
kind: ConfigMap
metadata: 
  name: mosquitto-conf
data:
  mosquitto.conf: |
    persistence true
    persistence_location /mosquitto/data/
    listener 1883
    protocol websockets
    allow_anonymous true
    log_dest file /mosquitto/log/mosquitto.log
    log_dest stdout